name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Aztec Tools
        run: |
          export PATH="$HOME/.aztec/bin:$PATH"
          bash -i <(curl -s https://install.aztec.network)
      
      - name: Add Aztec to PATH
        run: echo "$HOME/.aztec/bin" >> $GITHUB_PATH

      - name: Compile contracts
        run: yarn compile

      - name: Generate TS artifacts
        run: yarn codegen

      - name: Run tests
        run: |
          # Start sandbox in the background
          aztec start --sandbox &
          # Give sandbox a moment to start up
          sleep 15
          # Run the tests
          yarn test
